export const SET_AUTH_DATA = 'SET_AUTH_DATA';
export const SWITCH_COLOR_THEME = 'SWITCH_COLOR_THEME';
export const SET_SCROLLED = 'SET_SCROLLED';

export const SET_IS_FETCHING = 'SET_IS_FETCHING';

export const DELETE_WORD_FROM_STATE = 'DELETE_WORD_FROM_STATE';
export const ADD_WORD_TO_STATE = 'ADD_WORD_TO_STATE';
export const ADD_SET = 'ADD_SET';
export const UPDATE_WORD_IN_STATE = 'UPDATE_WORD_IN_STATE';
export const SET_SEARCH_INPUT = 'SET_SEARCH_INPUT';
export const FILTER_SET = 'FILTER_SET';
export const PUSH_TO_ADDED_MEANINGS = 'PUSH_TO_ADDED_MEANINGS';
export const DELETE_FROM_ADDED_MEANINGS = 'DELETE_FROM_ADDED_MEANINGS';
export const SET_ADDED_MEANINGS = 'SET_ADDED_MEANINGS';
