export const SET_AUTH_DATA = 'SET_AUTH_DATA';

export const SET_IS_FETCHING = 'SET_IS_FETCHING';

export const DELETE_WORD_FROM_STATE = 'DELETE_WORD_FROM_STATE';
export const ADD_WORD_TO_STATE = 'ADD_WORD_TO_STATE';
export const ADD_SET = 'ADD_SET';
